[package]
name = "ingesto-database-reader"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = [ "runtime" ]
runtime = [ "types" ]
types = []

[dependencies]
shared = { path = "../../shared", features = [ "runtime" ] }
