[package]
name = "ingesto-file-reader"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = [ "runtime" ]
runtime = [
	"types",
	"dep:shared",
]
types = [ "dep:shared" ]

[dependencies]
shared = { path = "../../shared", optional = true, default-features = false }

notify = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
